# Generated by Django 4.2.30 on 2026-06-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('quantidade_estoque', models.IntegerField()),
                ('quantidade_vendido', models.IntegerField()),
                ('notas_usuario', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
