# Generated by Django 4.2.30 on 2026-06-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_produtos_delete_produto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produtos',
            new_name='Produto',
        ),
    ]
