# Generated by Django 4.2.30 on 2026-06-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_rename_produtos_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade_vendido',
            field=models.IntegerField(default=0),
        ),
    ]
