# Generated by Django 6.0.6 on 2026-06-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_produto_quantidade_vendido'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='disponivel_produto',
            field=models.BooleanField(default=True),
        ),
    ]
