# Generated by Django 4.2.30 on 2026-06-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_produto_quantidade_vendido'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='produto_disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
